[package]
name = "portlist"
version = "0.1.0"
authors = ["KaJIH <kajih@home>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
netstat2 = "*"
